### ISSUE TITLE
Multiple datasets and dynamic forms

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/platform#343]
Our dynamic forms and datasets feature is finally ready for the next release! But before we can merge this into master, there are a few minor issues that we need to resolve:

**Issues that need to be resolved before merging `develop` into `master`**
 - [x] Integrate multiple datasets (issue #141 and resolved by PR #254)
 - [x] Create the dynamic form (resolved by PR #254)
 - [x] Fix the occasional 500 error caused by a missing dataset_id in views.api (issue #375, branch `goldpbear/missingDatasetIdError`)
 - [x] Handle case where dynamic form is used with single category (issue #373, branch `goldpbear/dynamicFormSingleCategory`)
 - [x] Remove duplicate declaration of datasetSlug parameter in config (issue #372, branch `goldpbear/duplicateDatasetSlugParam`) 
 - [x] Prevent reappearance of map drag message on category change (issue #382, branch `goldpbear/multipleMapDragMessages`)
 - [x] Update the other flavor configs to use the new settings (ie we have a new layer type called `place` in the map setting for our community reports) (issue #374, branch `goldpbear/dynamicFormForFlavors`) (_NOTE: let's make a final pass over the flavor configs right before we merge_)
 - [x] Update the docs for our config (issue #349, branch `documentationUpdates-349`)

**Issues that do _not_ need to be resolved before merging `develop` into `master`**
- [x] Fix the PlaceListView filter to search over the model's fields defined in our dynamic forms (issue #383)
- [x] Update the legend to enable toggling community reports (currently under MapView, which toggles the `shareabouts` layer type)

Not that this is a meta issue, so we can make separate issues for each of the above items.

**Comment by LukeSwart** [comment]
Note that this implementation is blocking #292 and #26, but those issues are not preventing us from merging `develop` with `master`.
