### ISSUE TITLE
Place detail view and list view updates

### ISSUE THREAD

**Issue by goldpbear** [smartercleanup/platform#434]
A few tweaks to the way dynamic form responses are rendered in place detail views and in the list view:

- [x] Show the label property of checkboxes and radio buttons, instead of the internally used value
- [x] Display checkbox selections as a bulleted list
- [x] Use a heavier typeface (maybe an h4 tag) for `display_prompt` fields
- [x] Hide duplicated `title` field
- [x] Hide labels for unanswered questions
